[platformio]
default_envs = fixed_ratio

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = adafruit_feather_adalogger
framework = arduino
upload_protocol = picotool
monitor_speed = 115200
monitor_filters = send_on_enter
lib_deps =
    adafruit/RTClib @ ^2.1.4
    adafruit/Adafruit MPR121 @ ^1.1.3
    adafruit/Adafruit NeoPixel @ ^1.12.0
    arduino-libraries/Stepper @ ^1.1.3

[env:fixed_ratio]
build_flags = -DMOUSEHOUSE_TASK_FIXED_RATIO

[env:free_feeding]
build_flags = -DMOUSEHOUSE_TASK_FREE_FEEDING

[env:go_nogo_automated]
build_flags = -DMOUSEHOUSE_TASK_GO_NOGO_AUTOMATED

[env:setup_debug]
build_flags = -DMOUSEHOUSE_TASK_SETUP_DEBUG
