// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// ---------- //
// camera_ttl //
// ---------- //

#define camera_ttl_wrap_target 7
#define camera_ttl_wrap 13
#define camera_ttl_pio_version 0

static __pio_const uint16_t camera_ttl_program_instructions[] = {
    0x80a0, //  0: pull   block
    0xa0c7, //  1: mov    isr, osr
    0x80a0, //  2: pull   block
    0xa047, //  3: mov    y, osr
    0xe000, //  4: set    pins, 0
    0x0085, //  5: jmp    y--, 5
    0x80a0, //  6: pull   block
            //     .wrap_target
    0xe001, //  7: set    pins, 1
    0xc000, //  8: irq    nowait 0
    0xa026, //  9: mov    x, isr
    0x004a, // 10: jmp    x--, 10
    0xe000, // 11: set    pins, 0
    0xa047, // 12: mov    y, osr
    0x008d, // 13: jmp    y--, 13
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program camera_ttl_program = {
    .instructions = camera_ttl_program_instructions,
    .length = 14,
    .origin = -1,
    .pio_version = camera_ttl_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config camera_ttl_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + camera_ttl_wrap_target, offset + camera_ttl_wrap);
    return c;
}

static inline void camera_ttl_program_init(PIO pio, uint sm, uint offset,
                                           uint pin, float clock_divider) {
  pio_gpio_init(pio, pin);
  pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
  pio_sm_config config = camera_ttl_program_get_default_config(offset);
  sm_config_set_set_pins(&config, pin, 1);
  sm_config_set_clkdiv(&config, clock_divider);
  pio_sm_init(pio, sm, offset, &config);
  pio_sm_set_pins_with_mask(pio, sm, 0, 1u << pin);
}

#endif

